version: '3.9'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "33117:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: ./server
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8054:8054"
    command: sh -c "node dist/src/run-migrations.js || node dist/src/run-migrations.cjs || true && node dist/main.js"

  ui:
    build:
      context: ./ui
    env_file:
      - .env
    depends_on:
      - server
    ports:
      - "9807:9807"

volumes:
  mysql_data:
